### ISSUE TITLE
MQTT Route interprets JSON where it shouldn't

### ISSUE THREAD

**Issue by crasbe** [bevywise-networks/mqttroute-mongodb-connector#1]
Hello,

I tried sending JSON documents via MQTT Route and noticed a significant bug: When JSON documents (or even simple strings that follow the general JSON style) are sent via MQTT Route, MQTT Route will interpret these and the content of the "data" variable custom_store.py will be altered.

Steps to reproduce:
1) Setup MQTT Route with the mqttroute-mongodb-connector.
2) Send a message similar to '{"foo" : "bar" }' (without ').
3) Look into the MongoDB database and find the altered tags.
You would expect a tag similar to 'message: "{"foo" : "bar"}"'. However this is not the case and you'll find a tag that will be foo: "bar".

Debugging aids:
When you insert a simple 'print(data)' into the 'handle_Received_Payload' function in custom_store.py, you'll find that it will print something similar the following:
{'sender': 'MQTT_FX_Client', 'unixtime': 1523285270, 'topic': 'test/testtopic', timestamp': '2018-04-09 16:47:50', u'foo': u'bar'}
The 'message' tag is missing and the 'foo' tag has been added.

This indicates, that it's in fact not a bug in the mqttroute-mongodb-connector but a bug in MQTT Route itself, as the data variable comes pretty much directly from MQTT Route.
The bug is NOT limited to MQTT_FX_Client, I've reproduced it with a simple Python script using the Paho MQTT implementation.

I'm using the lastest Trial Version.

I'm available for questions regarding the bug.

Greetings,
Chris

**Comment by bevywise** [comment]
Dear Chris, 

Thanks for raising this. 

This is an expected behavior. 

When a customer sends a single level of JSON data we want to add them federated for their easier query. 

But when the data is at multiple level,  we expect the user to parse it using the python code and store it the way they wanted. 

I believe we need to capture it clearly on the help documentation.   

Do let me know if you feel we need to change our implementation on the MQTTRoute. 

Thanks for trying the connector and MQTTRoute. 

Cheers.
